server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
            # JWT 검증
            - AuthorizationHeaderFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*),/$\{path}


# jwt
app.jwt-secret: zd0RObpHNTie25ScIK1BbSYIDwwpXq6wD7osjNa6HslJxdVgYXR9PQSsmoSjOZQs7eUq25wJyRs55om3ledb45ErtxLiwBKDPF3RKAAjs3pxrLANZNY4TDvmagEHSplH4ozPZa8rdxYFjzsinrnh5SDf9iW1IhJNGiCGtL7Hj6mCGPV4hilmbZBkiym0Q5NwoqcRckyvqV87K3b2mwoxwZROyeOokCVI37Afs9LS4T0PWbSiIgQegI2OWRcgu8ZxfzNHIyANrADoMvHuMxJ2fMRbE4s8crGr0u9J2KxulbS8HzDt7mvm8nyMr0VDrC5s6eb8ZJClUvtB565ctBzBY7op8k2zW713mdclWOGRkasqgyCJ9cl7jKws5z12G352hhoe655qfyQw6tgfFCmZmTrrstu8wzbOQA2WF7nVFerMHI1nkonGhO8JiCSPc4D2EFZkNnfsBHejpgGJE4qVSzFacyZoCDrhirB5OQypyNIX4pHIt8EmHjxUSxjuaKLt


# 유레카 서버 등록
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true